#!/usr/bin/env bash

if [ "$1" == "a" ]; then
	rm ~/.dotfiles/.config/nvim
	ln -s ~/.dotfiles/.config/nvima ~/.dotfiles/.config/nvim

	rm ~/.cache/nvim
	[ -d ~/.cache/nvima ] && ln -s ~/.cache/nvima ~/.cache/nvim

	cd ~/.dotfiles && stow .
elif [ "$1" == "b" ]; then
	rm ~/.dotfiles/.config/nvim
	ln -s ~/.dotfiles/.config/nvimb ~/.dotfiles/.config/nvim

	rm ~/.cache/nvim
	[ -d ~/.cache/nvimb ] && ln -s ~/.cache/nvimb ~/.cache/nvim

	cd ~/.dotfiles && stow .
fi

